### ISSUE TITLE
Bug d'affichage

### ISSUE THREAD

**Issue by FranciscoKevin** [WildCodeSchool/tours-php-2009-project3-amon#36]
Vous avez un bug d'affichage dans la partie bibliothèque de type 'hover' en CSS
Quand on clique sur le menu ou les catégories la page saute.

**Comment by rickifox** [comment]
Nous ne parvenons à reproduire le bug merci de bien vouloir retester dans l'après-midi et de réouvrir une issue s'il se reproduisait.
