### ISSUE TITLE
Step names in article creation form

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#38]
Il serait plus compréhensible, à mon sens, d'indiquer à quoi sert l'étape 1/2 directement après "Etape 1/2".
J'ai eu un peu de mal à comprendre que "Nom" et "Description" était spécifiquement pour la photo pré-loader et non pour l'article lui même.
![Capture d’écran du 2021-02-08 11-30-57](https://user-images.githubusercontent.com/64312943/107208031-4e885080-6a01-11eb-83f4-60efd3546d4b.png)

**Comment by KevinRoig** [comment]
Ok, modified.
