### ISSUE TITLE
Title length in article creation form

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#39]
On peut mettre un titre d'article beaucoup trop long dans le formulaire.
![Capture d’écran de 2021-02-08 11-24-58](https://user-images.githubusercontent.com/64312943/107207191-4f6cb280-6a00-11eb-9d06-0ae45121c481.png)

**Comment by KevinRoig** [comment]
Ok, modified to max 255 characters but there is no word with so many characters any way! If you have a space, it goes to the next line.
![image](https://user-images.githubusercontent.com/70197762/107367949-389d8d00-6ae0-11eb-8b26-bd2030cf2a77.png)
