### ISSUE TITLE
Image titlte or image description

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#40]
Si je mes trop de texte dans **titre** ou **description**, j'ai une erreur 500
![Capture d’écran du 2021-02-08 11-39-39](https://user-images.githubusercontent.com/64312943/107208918-7fb55080-6a02-11eb-8e0e-1ce1144d39b2.png)

**Comment by KevinRoig** [comment]
Je n'ia pas réussi à reproduire l'erreur, à voir si ça revient.

**Comment by rickifox** [comment]
Problem solved with server side error message if one of them is too long
