### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#41]
Si je sélectionne une image trop lourde, j'ai une erreur 403 (1,3 Mb pour le test ici)
![Capture d’écran du 2021-02-08 11-38-41](https://user-images.githubusercontent.com/64312943/107209135-b7bc9380-6a02-11eb-8bb1-efd8c4da99e7.png)

**Comment by KevinRoig** [comment]
Normalement c'est ok jusqu'à 2Mo, tu peux refaire des tests pour voir stp?

**Comment by thocle86** [comment]
J'ai testé plein de fichier, au-dessus de **1MB** ça plante

**Comment by KevinRoig** [comment]
En attente de retour de Romain, voir si c'est l'hébergement qui bloque.

**Comment by rickifox** [comment]
Marche parfaitement sur nos environnements de dev, probabalement lié à des limitations sur l'environnement de prod
