### ISSUE TITLE
Article title or article description

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#42]
Si je mes trop de texte dans titre ou description, j'ai une erreur 500
![Capture d’écran du 2021-02-08 11-39-39](https://user-images.githubusercontent.com/64312943/107210212-1cc4b900-6a04-11eb-8aec-24e2c86b3a23.png)

**Comment by KevinRoig** [comment]
Already an issue (#40)
