### ISSUE TITLE
Image missing in gallery

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#43]
J'ai ajouté un article avec une image via le formulaire, l'article est dans l'actualité car j'ai choisi actualité dans le formulaire.
La photo est dans la catégorie **verrières** mais pas dans la catégorie **toutes les catégories** ? est-ce normal ?
![Capture d’écran de 2021-02-08 12-00-11](https://user-images.githubusercontent.com/64312943/107211511-f273fb00-6a05-11eb-9e93-509f6cfa91e3.png)
![Capture d’écran de 2021-02-08 12-00-36](https://user-images.githubusercontent.com/64312943/107211521-f869dc00-6a05-11eb-97f3-53d6a0890988.png)

**Comment by KevinRoig** [comment]
Non, ce n'est pas normal. Il manquait un "s" à Verrières dans le code....
Fixed.
