### ISSUE TITLE
Redirection after delete in gallery

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#44]
Je suis dans la catégorie **Toutes les catégories**, si je supprime une photo je suis redirigé dans la catégorie de la photo précédemment supprimée.
Dans l'exemple ci-dessous, je supprime la photo airbnb, je suis redirigé vers sa catégorie, **Décoration**
![Capture d’écran de 2021-02-08 12-16-34](https://user-images.githubusercontent.com/64312943/107212846-d96c4980-6a07-11eb-8b5c-2803907a3084.png)
![Capture d’écran de 2021-02-08 12-16-39](https://user-images.githubusercontent.com/64312943/107212891-e721cf00-6a07-11eb-992a-087d92811e1c.png)

**Comment by KevinRoig** [comment]
Ok, but won't be changed, not so important (there is no "toutes catégories" category, so we can not go back there.
