### ISSUE TITLE
Photo location problem in the gallery

### ISSUE THREAD

**Issue by thocle86** [WildCodeSchool/tours-php-2009-project3-amon#45]
J'ai essayé par 2 fois d'ajouter une photo dans la catégorie **Brise-vue et Pare-soleil**, mais les 2 photos ne sont que dans la catégorie **Toutes les catégories**
![Capture d’écran de 2021-02-08 12-15-04](https://user-images.githubusercontent.com/64312943/107213132-3f58d100-6a08-11eb-8765-0bd9bd871489.png)
![Capture d’écran de 2021-02-08 12-14-58](https://user-images.githubusercontent.com/64312943/107213142-4384ee80-6a08-11eb-8691-6e9fe481353a.png)

**Comment by KevinRoig** [comment]
Ok, fixed.
